/**
 * ==========================================================================
 * Copyright (c) 2021-2026 Sterfive - etienne.rossignon@sterfive.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 * ==========================================================================
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import {
    BrokerDataSetWriterTransportDataType,
    BrokerWriterGroupTransportDataType,
    JsonWriterGroupMessageDataType,
    NetworkAddressUrlDataType,
    PubSubConfigurationDataType,
    PubSubConnectionDataType
} from "node-opcua-types";
import should from "should";
import { decodeOPCUA_JSON, decodeOPCUA_JSONOld, opcuaJsonEncodeExtensionObjectBody, type Pojo } from "../source/index.js";
import { JsonEncodingScheme } from "../source/json_encoding_scheme.js";

describe("it should be possible to read file generated by the .NTCore stack", () => {
    it("test1", async () => {
        const jsonAsText = await readFile(path.join(import.meta.dirname, "./fixture/third_party_json.json"), "ascii");

        const json = JSON.parse(jsonAsText);
        const extObj = decodeOPCUA_JSONOld<PubSubConnectionDataType>("PubSubConnectionDataType", json);
        should(extObj?.name).eql("localhost");
        should(extObj?.enabled).eql(true);
        should(extObj?.writerGroups?.length).eql(3);
        should(extObj?.writerGroups?.[0].publishingInterval).eql(60000);
        should(extObj?.address).be.instanceof(NetworkAddressUrlDataType);
        if (extObj?.address instanceof NetworkAddressUrlDataType) {
            should(extObj?.address.url).eql("mqtt://localhost:1883/");
        }
        should(extObj?.writerGroups?.[0].dataSetWriters?.length).eql(1);
        should(extObj?.writerGroups?.[0].dataSetWriters?.[0].name).eql("identity");

        should(extObj?.writerGroups?.[0].dataSetWriters?.[0].transportSettings).be.instanceOf(BrokerDataSetWriterTransportDataType);

        ///  console.log(extObj?.toString());
    });

    it("test2", async () => {
        const jsonAsText = await readFile(path.join(import.meta.dirname, "./fixture/third_party_json.json"), "ascii");
        const json = JSON.parse(jsonAsText);

        const extObj = decodeOPCUA_JSON(PubSubConnectionDataType, json);

        should(extObj?.name).eql("localhost");
        should(extObj?.enabled).eql(true);
        should(extObj?.writerGroups?.length).eql(3);
        should(extObj?.writerGroups?.[0].publishingInterval).eql(60000);
        should(extObj?.address).be.instanceof(NetworkAddressUrlDataType);
        if (extObj?.address instanceof NetworkAddressUrlDataType) {
            should(extObj?.address.url).eql("mqtt://localhost:1883/");
        }
        should(extObj?.writerGroups?.[0].dataSetWriters?.length).eql(1);
        should(extObj?.writerGroups?.[0].dataSetWriters?.[0].name).eql("identity");

        should(extObj?.writerGroups?.[0].dataSetWriters?.[0].transportSettings).be.instanceOf(BrokerDataSetWriterTransportDataType);

        // console.log(extObj?.toString());
    });

    it("test3", async () => {
        const p = new PubSubConfigurationDataType({
            publishedDataSets: [],
            connections: [
                new PubSubConnectionDataType({
                    address: new NetworkAddressUrlDataType({}),
                    writerGroups: [
                        {
                            writerGroupId: 1,
                            messageSettings: new JsonWriterGroupMessageDataType({}),
                            transportSettings: new BrokerWriterGroupTransportDataType({})
                        }
                    ]
                })
            ]
        });

        const json = opcuaJsonEncodeExtensionObjectBody(p, JsonEncodingScheme.DeprecatedReversible);
        // console.log(JSON.stringify(json, null, " "));

        const reloaded = decodeOPCUA_JSON(PubSubConfigurationDataType, json as Pojo);

        reloaded.should.eql(p);
    });
});
