
test-cov: istanbul

istanbul:
	istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec --recursive --timeout 30000 --bail test

coveralls:
	cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

# literate_programming stuff
LP= "../node_modules/.bin/literate-programming"
LP_WIN= "..\\node_modules\\.bin\\literate-programming.cmd"


examples:
	( cd documentation ; $(LP) creating_a_server.md )
	( cd documentation ; $(LP) creating_a_client.md )
	( cd documentation ; $(LP) create_a_weather_station.md )
	( cd documentation ; $(LP) server_with_da_variables.md )
	( cd documentation ; $(LP) server_with_method.md )

# construct the API javascript documentation
doc: examples
	mkdir -p tmptmp/autogenerated
	node code_gen/makedoc.js  > tmptmp/autogenerated/a.js
	autodoc tmptmp/autogenerated/a.js
	# jsdoc -v tmptmp/autogenerated/a.js lib/nodeid.js -d=tmptmp/api_doc_js_doc
	yuidoc 

yuidoc:
	npm install yuidocjs -g

build_tools:
	npm install minifyjs -g
	npm install browserify -g

build:
	brfy.bat

ug:
	node -e 'var NodeUglifier= require("node-uglifier");(new NodeUglifier("bin/simple_server.js")).uglify().exportToFile("a.js");'
