

test-cov: istanbul

istanbul:
	npx -y nyc@15 node -r source-map-support/register  ${SECURITY_REVERT_CVE_2023_46809} --max_old_space_size=8192 ./packages/run_all_mocha_tests.js  
	npx -y nyc@15 report --reporter=lcov --reporter=html 

# literate_programming stuff
LP= "../node_modules/.bin/literate-programming"
LP_WIN= "..\\node_modules\\.bin\\literate-programming.cmd"


examples:
	( cd documentation ; $(LP) creating_a_server.md )
	( cd documentation ; $(LP) creating_a_client_typescript.md )
	( cd documentation ; $(LP) creating_a_client_callback.md )
	( cd documentation ; $(LP) create_a_weather_station.md )
	( cd documentation ; $(LP) server_with_da_variables.md )
	( cd documentation ; $(LP) server_with_method.md )

# construct the API javascript documentation
doc: examples
	mkdir -p tmptmp/autogenerated
	node code_gen/makedoc.js  > tmptmp/autogenerated/a.js
	autodoc tmptmp/autogenerated/a.js	
	# jsdoc -v tmptmp/autogenerated/a.js lib/nodeid.js -d=tmptmp/api_doc_js_doc
	yuidoc 

doc1:
	npx yuidocjs
# npx yuidocjs -t node_modules/yuidoc-bootstrap-theme -H node_modules/yuidoc-bootstrap-theme/helpers/helpers.js

yuidoc:
	npm install yuidocjs -g

build_tools:
	npm install minifyjs -g
	npm install browserify -g

build:
	brfy.bat

ug:
	node -e 'var NodeUglifier= require("node-uglifier");(new NodeUglifier("bin/simple_server.js")).uglify().exportToFile("a.js");'
