recursive: true
require:
  - ../../node_modules/should
  - ../../node_modules/ts-node/register
timeout: 20000
enable-source-maps: true
spec:
  - test/**/*.ts
  - test/**/*.js
bail: true
parallel: false
jobs: 32