bail: true
timeout: 20000
recursive: true
require:
  - ../../node_modules/source-map-support/register
  - ../../node_modules/ts-node/register/transpile-only
  - ../../node_modules/should
spec:
  - test/**/*.ts
