module.exports = {
    nodesets: {
        adi: "nodeset:adi",
        di: "nodeset:di",
        standard: "nodeset:standard",
        gds: "nodeset:gds",
        autoId: "nodeset:autoId",
        robotics: "nodeset:robotics",
        machineVision: "nodeset:machineVision",
        packML: "nodeset:packML",
        machinery: "nodeset:machinery",
        cnc: "nodeset:CNC",
        commercialKitchenEquipment: "nodeset:commercialKitchenEquipment",
        ia: "nodeset:ia",
        machineTool: "nodeset:machineTool",
        woodWorking: "nodeset:woodWorking",
        eumabois: "nodset:eumabois",
        glass: "nodeset:glass",
        tightening: "nodeset:tightening",
        iolink: "nodeset:iolink",
        iolinkIODD: "nodeset:iolinkIODD",
        irdi: "nodeset:irdi",
        padim: "nodeset:padim",
        machineryProcessValues: "nodeset:machineryProcessValues",
        machineryResult: "nodeset:machineryResult",
    }
};
