import { AttributeIds } from "node-opcua";

export const itemsToMonitor1 = [
    { nodeId: "ns=2;s=Static_Scalar_Boolean", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Byte", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_ByteString", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_DateTime", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Time", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_SByte", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Int16", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_UInt16", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Int32", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_UInt32", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Int64", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_UInt64", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Float", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Double", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Duration", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Guid", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_LocaleId", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_LocalizedText", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_NodeId", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Number", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_UInteger", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_Integer", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_UtcTime", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_XmlElement", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_ImageBMP", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_ImageGIF", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Scalar_ImagePNG", attributeId: AttributeIds.Value },
];
export const itemsToMonitor2 = [

    { nodeId: "ns=2;s=Static_Array_Boolean", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Byte", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_ByteString", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_DateTime", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Time", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_SByte", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Int16", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_UInt16", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Int32", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_UInt32", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Int64", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_UInt64", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Float", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Double", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Duration", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Guid", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_LocaleId", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_LocalizedText", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_NodeId", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Number", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_UInteger", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_Integer", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_UtcTime", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_XmlElement", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_ImageBMP", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_ImageGIF", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Static_Array_ImagePNG", attributeId: AttributeIds.Value },


    { nodeId: "ns=2;s=ByteDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=DoubleDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Int16DataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Int32DataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Int64DataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt16DataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt32DataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt64DataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=SByteDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=StringDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=DateTimeDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=FloatDataItem", attributeId: AttributeIds.Value },

    { nodeId: "ns=2;s=DoubleArrayAnalogDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Int16ArrayAnalogDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt16ArrayAnalogDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt16ArrayAnalogDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt32ArrayAnalogDataItem", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=FloatArrayAnalogDataItem", attributeId: AttributeIds.Value },

    { nodeId: "ns=2;s=MultiStateDiscrete001", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=MultiStateDiscrete002", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=MultiStateDiscrete003", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=MultiStateDiscrete004", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=MultiStateDiscrete005", attributeId: AttributeIds.Value },

    { nodeId: "ns=2;s=TwoStateDiscrete001", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=TwoStateDiscrete002", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=TwoStateDiscrete003", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=TwoStateDiscrete004", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=TwoStateDiscrete005", attributeId: AttributeIds.Value },

    { nodeId: "ns=2;s=ByteMultiStateValueDiscrete", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=SByteMultiStateValueDiscrete", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Int16MultiStateValueDiscrete", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Int32MultiStateValueDiscrete", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=Int64MultiStateValueDiscrete", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt16MultiStateValueDiscrete", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt32MultiStateValueDiscrete", attributeId: AttributeIds.Value },
    { nodeId: "ns=2;s=UInt64MultiStateValueDiscrete", attributeId: AttributeIds.Value },
];

