require:
  - ../../node_modules/source-map-support/register
  - ../../node_modules/ts-node/register
  - ../../node_modules/should
recursive: true
bail: true
extension:
  - js
  - ts
timeout: 50000
# parallel: true
# jobs: 10
