var ActivateSessionResponse_Schema =  {
    documentation: "Activates a session with the server.",
    name: "ActivateSessionResponse",
    fields: [
        { name:"responseHeader",               fieldType:"ResponseHeader",   documentation:"A standard header included in all responses returned by servers."},
        { name:"serverNonce",                  fieldType:"ByteString",       documentation:"A random number generated by the server."},
        { name:"results",        isArray:true, fieldType:"StatusCode",       documentation:"Any errors during validation of the software certificates."},
        { name:"diagnosticInfos",isArray:true, fieldType:"DiagnosticInfo",   documentation:"The diagnostics associated with the software certificates results."}

    ]
};
exports.ActivateSessionResponse_Schema = ActivateSessionResponse_Schema;
