recursive: false
require:
- ../../node_modules/source-map-support/register
- ../../node_modules/ts-node/register
- ../../node_modules/should
timeout: 20000
extension:
   - js
   - ts
spec: test/**/*.ts
bail: true
