require:
  - ../../node_modules/source-map-support/register
  - ../../node_modules/ts-node/register
  - ../../node_modules/should
#  - ../../node_modules/tsconfig-paths/register
extension:
  - ts
recursive: true
timeout: 20000
enable-source-maps: true
